name = "integrated-site"
main = ".vercel/output/static/_worker.js/index.js"
compatibility_date = "2024-10-26"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[pages]
project_name = "integrated-site"
production_branch = "main"

[assets]
directory = ".vercel/output/static"
